FOGL-7694 username and password config items added and its usage
fledge-iot/fledge-north-opcuaclient pull request #10
Opened 2023-05-11 10:15 UTC by ashish-jabble

**Pending items**
- [ ] Security Modes and Policy
- [ ] Documentation updation

2023-05-16 14:29 UTC, MarkRiddoch approved these changes

2023-05-18 15:53 UTC, RVerhoeff commented on docs/index.rst
> +  - **Security Mode**: Specify the OPC/UA security mode that will be used to communicate with the OPC/UA server.
The terms OPC UA, OPC/UA and OPCUA all appear in the document. I suggest OPC UA everywhere.

2023-05-18 15:54 UTC, RVerhoeff commented on docs/index.rst
>          .. code-block:: JSON
Show or explain how multiple assets and multiple datapoints in an asset appear.

2023-05-18 15:55 UTC, RVerhoeff commented on docs/index.rst
> +  - **Server Public Certificate**: (Optional) The name of the public certificate of the OPC/UA server specified in the *OPCUA Server URL*. This must either be a DER or PEM format certificate file.
For all the certificate and key files: You must include the file extension (_mycert.der_ or _mycert.pem_). Do not include the file's directory name.

2023-05-18 15:56 UTC, RVerhoeff commented on docs/index.rst
> +Typically the Certificate Authorities certificate is retrieved and uploaded to the Fledge Certificate Store along with the certificate from the OPC/UA server that has been signed by that Certificate
Explain how self-signed certificates are different. They are not signed by a Certificate Authority. The system manager must copy the server certificate to the Fledge Certificate Store, and the client certificate to the server's trusted certificate store.

2023-05-18 15:57 UTC, RVerhoeff commented on docs/index.rst
> +|OpenSSL| may be used to generate and convert the keys and certificates required.
At the end of this paragraph, add "Copy the _ssl.conf_ file in this example to your own system when using the _openssl_ commands below to generate certificates."

2023-05-18 15:58 UTC, RVerhoeff commented on docs/index.rst
> +    subjectAltName should be same as your OPCUA server Application URI.
Not quite correct. It should be "subjectAltName should include your OPC UA server Application URI. This URI can be created in the client certificate by setting the value of the URI token in subjectAltName in the ssl.conf file."

2023-05-18 15:59 UTC, RVerhoeff commented on docs/index.rst
> +a) via GUI (Recommended way)
In this section, use "Fledge GUI" instead of just "GUI."

2023-05-18 15:59 UTC, RVerhoeff commented on docs/index.rst
> +b) via Manually
No need to use "via." Say "Using the Fledge GUI" for part 1, and "Manually" for part 2.

2023-05-18 15:59 UTC, RVerhoeff commented on docs/index.rst
> +- Copy the certificates and place in the `$FLEDGE_DATA/etc/certs/` or `$FLEDGE_ROOT/data/etc/certs/` directory. And if certificate in PEM format then place in the `$FLEDGE_DATA/etc/certs/pem/` or `$F
The second sentence begins "And if certificate in PEM format then place in the…" Instead, try "If the certificate is in PEM format, place it in the…"

2023-05-19 18:03 UTC, RVerhoeff commented on docs/index.rst
> +Typically the Certificate Authorities certificate is retrieved and uploaded to the Fledge Certificate Store along with the certificate from the OPC UA server that has been signed by that Certificate
This paragraph appears to have contradictions. If I may offer an alternative: "Typically a Certificate Authority issues a client certificate and private key for the plugin which are imported into the Fledge Certificate Store along with a certificate from the OPC UA server. It is also possible to use self-signed certificates. In all cases, the system manager must copy the server certificate to the Fledge Certificate Store and the client certificate to the server's trusted certificate store. Do not copy the client private key to any other system."

2023-05-19 18:06 UTC, RVerhoeff requested changes
Very good. A clarification is needed for the first paragraph of Certificate Management.

2023-05-22 14:45 UTC, RVerhoeff approved these changes
All good!

2023-05-23 03:39 UTC, merged