FOGL-7159
fledge-iot/fledge-north-opcuaclient pull request #3
Opened 2022-12-02 13:35 UTC by ashish-jabble

2022-12-02 14:00 UTC, MarkRiddoch requested changes

2022-12-02 14:00 UTC, MarkRiddoch commented on python/fledge/plugins/north/opcuaclient/opcuaclient.py
> +_LOGGER = logger.setup(__name__, level=logging.INFO)
Please revert this before checking in

2022-12-02 15:54 UTC, ashish-jabble commented on python/fledge/plugins/north/opcuaclient/opcuaclient.py
> +_LOGGER = logger.setup(__name__, level=logging.INFO)
@MarkRiddoch I don't see any reason to revert. Any specific reason? 
Default python level is warn. I have changed the python level to INFO (better) and also removed  info logs which were placed in a file which is talking more about testing/debug purpose and some of them are converted to DEBUG.

2022-12-02 18:16 UTC, RVerhoeff commented on python/fledge/plugins/north/opcuaclient/opcuaclient.py
> +            _LOGGER.debug('processing payloads')
It would be helpful to include the size of the payloads collection in this message.

2022-12-02 20:15 UTC, RVerhoeff commented on python/fledge/plugins/north/opcuaclient/opcuaclient.py
>              datavalue = ua.DataValue(self._value_to_variant(payload_block["value"], payload_block["type"]))
I still had to add _SourceTimestamp_ to the _DataValue_ constructor to get this to work. Were you not intending to address this right now?

2022-12-02 20:17 UTC, RVerhoeff approved these changes

2022-12-05 10:53 UTC, Mohit04tomar approved these changes

2022-12-05 13:57 UTC, MarkRiddoch approved these changes

2022-12-05 13:57 UTC, MarkRiddoch commented on python/fledge/plugins/north/opcuaclient/opcuaclient.py
> +_LOGGER = logger.setup(__name__, level=logging.INFO)
As long as we are not flooding the logs then fine.

2022-12-05 15:32 UTC, merged