FOGL-7159 Read the docs documentation added & other textual changes
fledge-iot/fledge-north-opcuaclient pull request #5
Opened 2022-12-09 07:37 UTC by ashish-jabble

2022-12-11 17:29 UTC, RVerhoeff commented on README.md
> +A Python plugin for Fledge that sends data north to with an OPC UA Client to a OPC UA Server.
Fix: to with an OPC UA Client

2022-12-11 17:31 UTC, RVerhoeff commented on docs/index.rst
> +North OpcuaClient
I think this should be _OPC UA Client North Plugin_

2022-12-11 18:08 UTC, RVerhoeff commented on docs/index.rst
> +      - **OPCUA Server URL**: The url of the OPC UA Server from which data will be extracted. The URL should be of the form opc.tcp://...
...OPC UA Server to which data will be sent.

2022-12-11 18:09 UTC, RVerhoeff commented on docs/index.rst
> +      - **Register Map**: The register map defines which are set of locations in the OPC UA object hierarchy.
You should elaborate on the structure of the JSON. The outer names are Asset names. The inner names are Datapoint names.

2022-12-11 18:10 UTC, RVerhoeff requested changes
A few recommendations

2022-12-12 14:39 UTC, RVerhoeff commented on docs/index.rst
> +      - **Map**: A map for asset datapoints/attributes to OPC UA node objects. A map JSON structure be like the outer names are Asset names and the inner names are Datapoint names.
be like -> in which

2022-12-12 14:40 UTC, RVerhoeff approved these changes
One minor change, otherwise good.

2022-12-12 15:26 UTC, MarkRiddoch requested changes

2022-12-12 15:26 UTC, MarkRiddoch commented on docs/index.rst
> +The *fledge-north-opcuaclient* plugin allows data to be sent with an OPC UA Client to a OPC UA Server.
an OPC UA server

2022-12-13 17:08 UTC, RVerhoeff approved these changes

2022-12-14 09:49 UTC, MarkRiddoch approved these changes

2022-12-14 09:50 UTC, merged